server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  spring:
    application:
      name: api-gateway
  cloud:
      gateway:
        routes:
          - id: quiz-service
            predicates:
                - Path=/quiz/**
            uri: lb://quiz-service
            filters:
              - AuthenticationFilter
          - id: question-service
            predicates:
                - Path=/question/**
            uri: lb://question-service
            filters:
              - AuthenticationFilter
          - id: auth-service
            predicates:
                - Path=/auth/**
            uri: lb://auth-service