server:
  port:
    8082

spring:
  application:
    name: quiz-service
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/quiz_management_system
    password: Ranjeet
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true