server:
  port: 8081
spring:
  application:
    name: quiz-service
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/quiz_management_system
    password: Ranjeet
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/